// Quest Actions
export const ADD_QUEST = 'ADD_QUEST'
export const FETCH_QUESTS = 'FETCH_QUESTS'
export const FETCH_QUESTS_SUCCESS = 'FETCH_QUESTS_SUCCESS'
export const FETCH_QUESTS_FAIL = 'FETCH_QUESTS_FAIL'

// User Actions
export const USER_LOGIN_SUBMITTED = 'USER_LOGIN_SUBMITTED'
export const USER_LOGIN_SUCCEDED = 'USER_LOGIN_SUCCEDED'
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'
export const USER_REGISTER_SUBMITTED = 'USER_REGISTER_SUBMITTED'
export const USER_REGISTER_SUCCEDED = 'USER_REGISTER_SUCCEDED'
export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED'
export const USER_AUTH_SUBMITTED = 'USER_AUTH_SUBMITTED'
export const USER_AUTH_SUCCEDED = 'USER_AUTH_SUCCEDED'
export const USER_AUTH_FAILED = 'USER_AUTH_FAILED'

// Submission Actions

// Comment Actions
